CREATE TABLE utilisateur(
   Id_UTILISATEUR INT,
   Nom VARCHAR(50) NOT NULL,
   Prénom VARCHAR(50) NOT NULL,
   email VARCHAR(50) NOT NULL,
   MDP VARCHAR(100) NOT NULL,
   image VARCHAR(50),
   PRIMARY KEY(Id_UTILISATEUR)
);

CREATE TABLE categorie(
   Id_CATEGORIE INT,
   categorie VARCHAR(50),
   PRIMARY KEY(Id_CATEGORIE)
);

CREATE TABLE SUJET(
   Id_SUJET INT,
   Nom_sujet VARCHAR(50) NOT NULL,
   Id_UTILISATEUR INT,
   Id_CATEGORIE INT NOT NULL,
   PRIMARY KEY(Id_SUJET),
   FOREIGN KEY(Id_UTILISATEUR) REFERENCES utilisateur(Id_UTILISATEUR),
   FOREIGN KEY(Id_CATEGORIE) REFERENCES categorie(Id_CATEGORIE)
);

CREATE TABLE Discussion(
   Id_DISCUSSION INT,
   commentaire VARCHAR(50) NOT NULL,
   datecommentaire DATE NOT NULL,
   Id_SUJET INT NOT NULL,
   PRIMARY KEY(Id_DISCUSSION),
   FOREIGN KEY(Id_SUJET) REFERENCES SUJET(Id_SUJET)
);

CREATE TABLE poste(
   Id_UTILISATEUR INT,
   Id_DISCUSSION INT,
   PRIMARY KEY(Id_UTILISATEUR, Id_DISCUSSION),
   FOREIGN KEY(Id_UTILISATEUR) REFERENCES utilisateur(Id_UTILISATEUR),
   FOREIGN KEY(Id_DISCUSSION) REFERENCES Discussion(Id_DISCUSSION)
);

CREATE TABLE choisis(
   Id_UTILISATEUR INT,
   Id_CATEGORIE INT,
   PRIMARY KEY(Id_UTILISATEUR, Id_CATEGORIE),
   FOREIGN KEY(Id_UTILISATEUR) REFERENCES utilisateur(Id_UTILISATEUR),
   FOREIGN KEY(Id_CATEGORIE) REFERENCES categorie(Id_CATEGORIE)
);
